import {articles} from '../content/articles.js';
import {link} from '../ui/components.js';
import {icon} from '../ui/icons.js';

export const editorialPages=['quem-somos','blog','duvidas',...articles.map(a=>'blog/'+a.slug)];
export const editorialTitle=page=>articles.find(a=>'blog/'+a.slug===page)?.title||({'quem-somos':'Quem somos',blog:'Blog',duvidas:'Perguntas frequentes'})[page];
const tryTool=(s,page,label)=>s.user||s.demo||page==='universidades'?link(page,label+' '+icon('arrow'),'button primary'):`<button class="button primary" data-action="demo" data-demo-page="${page}">${label} ${icon('arrow')}</button>`;
const intro=(label,title,description)=>`<header class="editorial-intro"><span class="eyebrow">${label}</span><h1>${title}</h1><p>${description}</p></header>`;
export const articleCard=(a,index=0)=>`<article class="journal-card journal-${a.color}"><a href="#blog/${a.slug}" aria-label="Ler: ${a.title}"><div class="journal-art" aria-hidden="true"><span class="journal-number">0${index+1}</span><span class="journal-orb">${icon(a.icon)}</span><span class="journal-line"></span></div><div class="journal-copy"><span class="eyebrow">${a.category} · GUIA PRÁTICO</span><h3>${a.title}</h3><p>${a.excerpt}</p><span class="tool-link">Ler o artigo ${icon('arrow')}</span></div></a></article>`;
export const journalPreview=()=>`<section class="journal-section" aria-labelledby="journal-title"><div class="section-heading"><div><span class="eyebrow">CADERNO DE VIAGEM</span><h2 id="journal-title">Boas perguntas.<br>Próximos passos.</h2></div>${link('blog','Todos os artigos '+icon('arrow'),'tool-link')}</div><div class="journal-grid">${articles.map(articleCard).join('')}</div></section>`;

const faqs=[
  ['Por onde eu começo?','Explore o catálogo ou experimente a demonstração. Quando quiser montar seu plano com seus próprios dados, crie uma conta e preencha seu perfil. Você pode atualizar notas, interesses e metas depois.'],
  ['Preciso criar conta para testar?','Não. A demonstração permite experimentar perfil, lista, escrita, prática e tarefas com instituições fictícias. Os dados da demonstração ficam neste navegador. Para salvar sua jornada na conta e acessar seus documentos, é necessário entrar.'],
  ['As 400 universidades são reais?','O catálogo conectado reúne 400 instituições dos Estados Unidos e do Canadá a partir dos materiais fornecidos ao projeto. As fichas indicam suas fontes. A demonstração usa um catálogo fictício menor. Confira requisitos e prazos atuais no site oficial de cada universidade.'],
  ['O que significam as categorias 3, 4 e 5?','Você organiza 3 escolhas sonho, 4 possíveis e 5 mais acessíveis. São categorias para planejar sua lista, não probabilidades de admissão. O MeuCampus não garante aprovação nem apresenta uma chance individual validada.'],
  ['Os assistentes de IA já estão disponíveis?','A ativação das respostas dos quatro assistentes está em preparação. Enquanto isso, você pode organizar seu perfil, consultar universidades, escrever rascunhos, praticar e acompanhar tarefas. A demonstração não faz consultas pagas de IA.'],
  ['Minha escola pode acompanhar minha conta?','Nesta versão, o espaço é individual. Você pode conversar com professores e familiares usando seu plano como referência, mas não existe um painel de escola com acesso automático aos seus dados.'],
  ['Onde encontro o contato do MeuCampus?','O e-mail e o telefone oficiais estão sendo preparados. Eles serão publicados aqui quando estiverem disponíveis.'],
];
export const faqList=(limit=faqs.length)=>`<div class="faq-list">${faqs.slice(0,limit).map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div>`;
export const homeClosing=s=>`${journalPreview()}<section class="home-faq"><div><span class="eyebrow">ANTES DE COMEÇAR</span><h2>Vamos tirar<br>algumas dúvidas?</h2>${link('duvidas','Ver todas as respostas '+icon('arrow'),'tool-link')}</div>${faqList(3)}</section><section class="closing-card"><div><span class="eyebrow">UM PASSO DE CADA VEZ</span><h2>Seu plano pode<br>começar hoje.</h2><p>Entre para organizar suas escolhas ou conheça primeiro como o MeuCampus funciona.</p></div><div class="actions">${link(s.user||s.demo?'painel':'entrar',s.user||s.demo?'Ir para meu painel':'Criar meu espaço','button primary')}${link('quem-somos','Conheça o MeuCampus','button secondary')}</div></section>`;

export function editorialView(s){
  if(s.page==='quem-somos')return `${intro('QUEM SOMOS','Um lugar para organizar<br>o que vem depois.','O MeuCampus é uma plataforma em construção para estudantes brasileiros que querem fazer faculdade fora. Reunimos pesquisa e preparação para ajudar você a transformar uma intenção em próximos passos.')}<section class="about-split"><div class="about-letter panel"><span class="eyebrow">NOSSO PONTO DE PARTIDA</span><h2>Uma candidatura<br>tem muita coisa.<br><em>Você vem primeiro.</em></h2><p>Notas, experiências, dúvidas, interesses. Antes de escolher uma universidade, existe uma pessoa tentando descobrir o próprio caminho.</p><p>O MeuCampus foi pensado para reunir essas partes em um espaço de trabalho: pesquisar opções, escrever com calma e lembrar o que precisa ser feito.</p></div><div class="about-principles">${[['01','Seu contexto importa.','Objetivos, experiências e condições de estudo fazem parte do plano. Seu perfil pode mudar e suas escolhas também.'],['02','Informação precisa de fonte.','As fichas preservam referências dos materiais. Requisitos e prazos precisam ser conferidos na instituição antes da candidatura.'],['03','Sua história continua sua.','Os textos partem de experiências verdadeiras. A organização ajuda você a trabalhar; a autoria e as decisões são suas.']].map(([n,t,p])=>`<article><span>${n}</span><div><h3>${t}</h3><p>${p}</p></div></article>`).join('')}</div></section><section class="audience-grid"><article class="panel"><span class="feature-icon">${icon('user')}</span><h2>Para quem está começando.</h2><p>Pesquise universidades e organize perfil, escolhas, essays, prática de SAT e tarefas sem precisar resolver tudo de uma vez.</p></article><article class="panel"><span class="feature-icon feature-2">${icon('school')}</span><h2>Com espaço para conversar.</h2><p>Use suas anotações para conversar com família e professores. Nesta versão, cada estudante cuida da própria conta; o acesso não é compartilhado automaticamente com a escola.</p></article></section><section class="closing-card"><div><span class="eyebrow">CONHEÇA NA PRÁTICA</span><h2>Antes de decidir,<br>explore.</h2><p>O catálogo está aberto para pesquisa. As ferramentas também têm uma demonstração.</p></div>${link('universidades','Ver universidades '+icon('arrow'),'button primary')}</section>`;
  if(s.page==='blog')return `${intro('BLOG MEUCAMPUS','Seu próximo capítulo<br>começa por aqui.','Guias para pesquisar com critério, encontrar sua voz e organizar a preparação. Uma leitura, um próximo passo.')}<section class="journal-grid blog-grid" aria-label="Artigos do blog">${articles.map(articleCard).join('')}</section><aside class="editorial-note">Conteúdo introdutório do MeuCampus, com referências oficiais para continuar a pesquisa. Consulte a instituição para requisitos e prazos da sua candidatura.</aside>`;
  if(s.page==='duvidas')return `${intro('PERGUNTAS FREQUENTES','Antes de dar<br>o próximo passo.','Como testar, montar sua lista e usar o espaço de preparação.')}<section class="faq-page" aria-label="Dúvidas sobre o MeuCampus">${faqList()}</section>`;
  const a=articles.find(a=>'blog/'+a.slug===s.page);
  if(!a)return '';
  return `<article class="reading-page">${link('blog','← Voltar ao blog','text-link')}${intro(a.category.toUpperCase(),a.title,a.excerpt)}<div class="article-meta">Redação MeuCampus · <time datetime="2026-09-24">24 de setembro de 2026</time></div><div class="article-layout"><div class="article-body">${a.sections.map(([title,text])=>`<section><h2>${title}</h2><p>${text}</p></section>`).join('')}<aside class="article-takeaway"><span class="eyebrow">PARA LEVAR COM VOCÊ</span><p>${a.takeaway}</p></aside><section class="article-sources"><h2>Continue nas fontes oficiais</h2><p>Referências consultadas em 24/09/2026. As sugestões de organização são editoriais do MeuCampus.</p>${a.sources.map(([title,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${title} ↗</a>`).join('')}</section></div><aside class="article-next panel"><span class="feature-icon">${icon(a.icon)}</span><h2>Da leitura<br>à prática.</h2><p>Leve uma ideia deste guia para o seu espaço de preparação.</p>${tryTool(s,...a.action)}</aside></div></article><section class="journal-section"><div class="section-heading"><h2>Continue a leitura.</h2>${link('blog','Todos os artigos','text-link')}</div><div class="journal-grid related-grid">${articles.filter(x=>x!==a).map(articleCard).join('')}</div></section>`;
}
