import {agents,groups,escapeHtml as e,wordCount} from '../domain.js';
import {configured} from '../data.js';
import {questions} from '../practice.js';
import {link,head,chip,empty} from '../ui/components.js';
import {homeView,dashboardView} from './overview.js';
import {catalogView,catalogResults} from './catalog.js';

export function createViews(s) {
const home=()=>homeView(s);
function login(){return `<section class="auth-layout"><div><span class="eyebrow">UM PASSO MAIS PERTO</span><h1>O mundo começa<br>com <em>você.</em></h1><p>Crie seu espaço para organizar notas, atividades e candidaturas.</p><div class="auth-note"><b>Seu contexto faz a diferença.</b><p>Vamos considerar o que você já conquistou, onde quer chegar e o apoio financeiro de que precisa.</p></div></div><form id="auth-form" class="panel auth-card"><h2>Entre na sua jornada</h2><p>Use seu e-mail e senha.</p><label>E-mail<input name="email" type="email" autocomplete="email" required></label><label>Senha<input name="password" type="password" autocomplete="current-password" minlength="8" required></label><button class="button primary" name="intent" value="login" ${configured?'':'disabled'}>Entrar →</button><button class="button secondary" name="intent" value="signup" ${configured?'':'disabled'}>Criar conta</button><button type="button" class="text-link" data-action="demo">Conhecer a demonstração</button><p class="small muted">${configured?'Confirme seu e-mail após criar a conta. O compartilhamento de dados com IA é opcional no perfil.':'Configure a conexão do Supabase para ativar o login.'}</p></form></section>`;}
const dashboard=()=>dashboardView(s,taskList);
function field(label,name,type='text',attrs=''){return `<label>${label}<input name="${name}" type="${type}" value="${e(s.profile?.[name]??'')}" ${attrs}></label>`;}
function profile(){return `${head('PASSO 01 · CONTE SUA HISTÓRIA','Seu ponto de partida.','Preencha o que sabe hoje. Você pode atualizar tudo depois.')}<form id="profile-form" class="panel profile-form"><h2>Sobre você</h2><div class="form-grid">${field('Nome *','full_name','text','required maxlength="120"')}${field('Ano ou etapa escolar *','school_year','text','required placeholder="Ex.: 2º ano do ensino médio"')}${field('Conclusão prevista','graduation_year','number','min="2020" max="2100"')}${field('Curso ou área de interesse *','interest','text','required')}<label>Países de interesse<input name="target_countries" value="${e(s.profile?.target_countries?.join(', ')||'')}" placeholder="Estados Unidos, Canadá..."></label>${field('Inglês e provas de proficiência','english_level')}</div><h2>Notas e resultados</h2><p class="small">Use a escala da sua escola. A meta de SAT não conta como resultado realizado.</p><div class="form-grid">${field('Média escolar','grade_average','number','min="0" max="100" step="0.01"')}${field('Nota máxima da escala','grade_scale','number','min="0.01" max="100" step="0.01"')}${field('SAT realizado','sat_actual','number','min="400" max="1600" step="10"')}${field('Meta de SAT','sat_target','number','min="400" max="1600" step="10"')}</div><h2>Atividades e experiências</h2><label>Extracurriculares<textarea name="extracurriculars" rows="6" maxlength="12000" placeholder="Descreva atividade, duração, responsabilidades, horas semanais e resultados reais.">${e(s.profile?.extracurriculars)}</textarea></label><h2>Condições para seu plano</h2><div class="form-grid">${field('Orçamento anual disponível','budget_annual','number','min="0" step="1"')}<label>Moeda<select name="budget_currency">${['BRL','USD','EUR','GBP','CAD'].map(x=>`<option ${x===(s.profile?.budget_currency||'BRL')?'selected':''}>${x}</option>`).join('')}</select></label>${field('Horas semanais para preparação','hours_week','number','min="1" max="80"')}</div><label class="checkbox"><input type="checkbox" name="needs_aid" ${s.profile?.needs_aid?'checked':''}>Preciso de bolsa ou auxílio financeiro.</label><label class="checkbox"><input type="checkbox" name="ai_consent" ${s.profile?.ai_consent?'checked':''}>Permito enviar meu perfil e os textos que eu escolher ao provedor de IA para orientação.</label><p class="small muted">Documentos pessoais não são enviados automaticamente. Você pode desativar esse compartilhamento a qualquer momento.</p><button class="button primary">Salvar meu perfil →</button></form>`;}
const universities=()=>catalogView(s);
function guideDetails(u){
 if(!u.guidance?.classification)return '';
 const g=u.guidance,score=s.profile?.sat_actual,target=Number(g.sat_meta)||null;
 return `<section class="guide-panel"><h3>Metas do guia</h3><p class="small">Sugestões editoriais do material. Não são requisitos nem previsão de aprovação.</p><div class="guide-metrics"><div><small>SAT sugerido</small><b>${e(g.sat_piso||'—')}–${e(g.sat_meta||'—')}</b></div><div><small>Média brasileira sugerida</small><b>${e(g.media_br_alvo||'—')} / 10</b></div><div><small>Admissão geral citada</small><b>${g.taxa_admissao_pct?e(g.taxa_admissao_pct)+'%':'Não informada'}</b></div></div><p class="small">A taxa de admissão geral reúne candidatos e anos diferentes; ela não mede sua chance individual.</p>${score&&target?`<p><b>SAT atual: ${score}.</b> ${score>=target?'Você alcançou a meta editorial. Isso não garante admissão.':`Faltam ${target-score} pontos para a meta editorial de ${target}.`}</p>`:''}<p><b>Direção sugerida:</b> ${e(g.alavanca_principal)}</p><details><summary>Classificação de atividades usada no guia</summary><p>${e(g.nivel_extracurricular)}</p><p class="small">Esta classificação é uma opinião editorial. Uma conquista nacional não é uma obrigação universal; seu contexto e oportunidades precisam ser considerados.</p></details></section>
 ${Object.entries(u.details||{}).map(([name,text])=>`<details class="dossier-section"><summary>${e(name)}</summary><p>${e(text)}</p></details>`).join('')}`;
}
function shortlist(){return `${head('PASSO 03 · CONSTRUA SUA LISTA','12 escolhas. O seu caminho.','Comece pelas 3 sonho, depois 4 possíveis e 5 mais acessíveis.',link('universidades','Explorar universidades ↗','button primary'))}<div class="notice-inline">Categorias são sua estratégia de candidatura. Não são uma previsão validada nem garantia de aprovação.</div><div class="shortlist-grid">${Object.entries(groups).map(([key,g],i)=>`<section class="panel list-group"><span class="eyebrow">0${i+1} · ${s.list.filter(x=>x.category===key).length}/${g.limit}</span><h2>${g.label}</h2><p>${['Onde você quer sonhar alto.','Possibilidades a explorar.','Opções mais favoráveis.'][i]}</p>${Array.from({length:g.limit},(_,slot)=>{const row=s.list.find(x=>x.category===key&&x.slot===slot+1);const u=s.universities.find(x=>x.id===row?.university_id);return row?`<div class="list-item"><span>${slot+1}</span><div><b>${e(u?.name||'Universidade em revisão')}</b><small>${e(u?.country)}</small></div><button data-remove="${e(row.university_id)}" aria-label="Remover ${e(u?.name)}">×</button></div>`:`<a class="list-slot" href="#universidades"><span>+</span> Sua próxima escolha</a>`;}).join('')}</section>`).join('')}</div>`;}
function taskList(tasks){return tasks.length?tasks.map(t=>`<div class="task"><label class="checkbox"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><span class="${t.done?'completed':''}">${e(t.title)}<small>${t.due_on?e(t.due_on.split('-').reverse().join('/')):'Sem prazo definido'}${t.university_id?' · '+e(s.universities.find(u=>u.id===t.university_id)?.name||'Universidade'):''}</small></span></label><button data-delete-task="${t.id}" aria-label="Excluir tarefa">×</button></div>`).join(''):empty('Seu próximo passo começa aqui.','Adicione uma ação na aba Candidaturas.');}
const universityOptions=(selected='')=>'<option value="">Geral</option>'+s.list.map(x=>s.universities.find(u=>u.id===x.university_id)).filter(Boolean).map(u=>`<option value="${u.id}" ${selected===u.id?'selected':''}>${e(u.name)}</option>`).join('');
function applications(){return `${head('DO PLANO À AÇÃO','Sua candidatura ganha forma.','Organize documentos, provas e entregas por universidade.')}<div class="two-columns"><section class="panel"><h2>Próximos passos</h2>${taskList(s.tasks)}</section><form class="panel stack" id="task-form"><h2>Adicionar uma ação</h2><label>O que precisa ser feito?<input name="title" required maxlength="250" placeholder="Ex.: solicitar histórico escolar"></label><label>Prazo<input name="due_on" type="date"></label><label>Universidade<select name="university_id">${universityOptions()}</select></label><button class="button primary">Adicionar ao meu plano +</button><p class="small muted">Confira os prazos na fonte oficial antes de registrar uma data.</p></form></div>`;}
function essays(){const draft=s.essays.find(x=>x.id===s.essayId);return `${head('SUA HISTÓRIA, SUA VOZ','Ideias que merecem espaço.','Desenvolva experiências verdadeiras, com a sua autoria.','<button class="button primary" data-action="new-essay">Novo essay +</button>')}<div class="essay-layout"><aside class="panel essay-index"><h3>Meus textos</h3>${s.essays.map(x=>`<button class="draft-link ${x.id===s.essayId?'selected':''}" data-essay="${x.id}"><b>${e(x.title)}</b><small>${wordCount(x.content)} palavras · versão ${x.version}</small></button>`).join('')||'<p class="small">Seu primeiro rascunho começa aqui.</p>'}</aside><section class="panel">${draft?`<form id="essay-form" class="stack"><label>Título<input name="title" required maxlength="200" value="${e(draft.title)}"></label><div class="form-grid"><label>Universidade<select name="university_id">${universityOptions(draft.university_id)}</select></label><label>Limite de palavras<input name="word_limit" type="number" min="1" max="10000" value="${draft.word_limit}" required></label></div><label>Enunciado<textarea name="prompt" rows="2">${e(draft.prompt)}</textarea></label><label>Seu texto<textarea name="content" id="essay-content" rows="15" maxlength="60000" placeholder="Comece por uma experiência que só você pode contar.">${e(draft.content)}</textarea></label><div class="section-title"><span id="word-count" class="small">${wordCount(draft.content)} / ${draft.word_limit} palavras</span><span class="small muted">Rascunho mantido nesta sessão. Salve para guardar.</span></div><div class="actions"><button class="button primary">Salvar rascunho</button><button class="button secondary" type="button" data-action="essay-feedback">Salvar e pedir feedback ✦</button></div></form>`:empty('Cada história começa com um rascunho.','Crie um essay para abrir seu espaço de escrita.')}</section></div>`;}
function sat(){const q=questions[s.question];return `${head('UM POUCO MELHOR A CADA ESTUDO','Encontre seu ritmo no SAT.','Pratique e entenda o raciocínio.')}<div class="metric-grid"><article><span>RESULTADO REALIZADO</span><strong>${s.profile?.sat_actual??'—'}</strong></article><article><span>META PESSOAL</span><strong>${s.profile?.sat_target??'—'}</strong></article><article><span>PRÁTICA REGISTRADA</span><strong>${s.attempts.length}</strong><small>tentativas · não equivale a uma nota SAT</small></article></div><div class="two-columns"><section class="panel"><div class="section-title">${chip(q.skill)}<small>${s.question+1} / ${questions.length}</small></div><h2 class="question">${q.prompt}</h2><form id="practice-form" class="stack">${q.options.map((answer,i)=>`<label class="answer-option"><input type="radio" name="answer" value="${i}" required ${s.feedback!==null?'disabled':''}> <b>${String.fromCharCode(65+i)}</b> ${e(answer)}</label>`).join('')}${s.feedback===null?'<button class="button primary">Conferir resposta →</button>':`<div class="feedback"><b>${s.feedback?'Você acertou.':'Vamos entender esse passo.'}</b><p>${e(q.explanation)}</p></div><button class="button secondary" type="button" data-action="next-question">Próxima questão →</button>`}</form></section><section class="panel tint"><span class="eyebrow">SEU PLANO DE ESTUDO</span><h2>Consistência primeiro.</h2><p>Disponibilidade: ${s.profile?.hours_week??'a definir'} horas por semana.</p><ol class="study-steps"><li>Revise os erros da última sessão.</li><li>Escolha uma habilidade para praticar.</li><li>Resolva questões e explique seu raciocínio.</li><li>Registre o que precisa retomar.</li></ol><button class="button secondary" data-agent="sat">Planejar com o tutor ✦</button><p class="small muted">Banco inicial: 4 exercícios autorais. Não é um simulado oficial.</p><div class="stack"><a class="text-link" href="https://satsuite.collegeboard.org/practice/student-question-bank" target="_blank" rel="noopener noreferrer">Banco oficial de questões ↗</a><a class="text-link" href="https://satsuite.collegeboard.org/practice/practice-tests" target="_blank" rel="noopener noreferrer">Simulados oficiais no Bluebook ↗</a></div></section></div>`;}
function assistants(){const [title,description]=agents[s.agent];const messages=s.messages.filter(x=>x.agent===s.agent);return `${head('QUATRO ESPECIALIDADES · O MESMO CONTEXTO','Um espaço para suas perguntas.','Orientação conectada ao seu perfil e às fontes disponíveis.')}<div class="agent-tabs">${Object.entries(agents).map(([key,[name]])=>`<button data-agent-tab="${key}" class="${key===s.agent?'selected':''}">${name}</button>`).join('')}</div><section class="panel conversation"><div class="section-title"><div><h2>✦ ${title}</h2><p>${description}</p></div></div><div class="chat-messages">${messages.map(m=>`<div class="message user"><small>VOCÊ</small><p>${e(m.question)}</p></div><div class="message assistant"><small>MEUCAMPUS · ${e(agents[m.agent][0])}</small><p>${e(m.answer)}</p>${(m.citations||[]).map(c=>`<small>Fonte: ${e(c.title)} · ${e(c.cycle)} ${c.url&&c.url.startsWith('https://')?`<a href="${e(c.url)}" target="_blank" rel="noopener noreferrer">Abrir ↗</a>`:e(c.document_name||'')+(c.page?' · p. '+e(c.page):'')}</small>`).join('')}</div>`).join('')||empty('Por onde começamos?','Quando faltarem fontes ou informações, o assistente deve deixar isso claro.')}</div><form id="chat-form"><label class="sr-only" for="chat-input">Sua pergunta</label><textarea id="chat-input" name="question" maxlength="6000" required rows="3" placeholder="O que você gostaria de entender?">${e(s.pendingQuestion||'')}</textarea><div class="section-title"><span class="small muted">${s.profile?.ai_consent?'Seu perfil autorizado será usado como contexto.':'Ative o consentimento de IA no seu perfil para conversar.'}</span><button class="button primary" ${s.busy?'disabled':''}>${s.busy?'Preparando resposta…':'Enviar ↗'}</button></div></form></section>`;}
function documents(){return `${head('SEUS DOCUMENTOS, EM UM SÓ LUGAR','Organize o que conta sua história.','Arquivos privados, acessíveis somente pela sua conta.')}<section class="panel"><form id="upload-form" class="upload-form"><label>Histórico, comprovante ou documento<input type="file" name="file" accept="application/pdf,image/png,image/jpeg" required></label><button class="button primary" ${s.demo?'disabled':''}>Enviar arquivo ↑</button></form><p class="small muted">PDF, PNG ou JPEG · até 10 MB. Os documentos não são enviados automaticamente às IAs.</p>${s.docs.map(d=>`<div class="document-row"><span>${e(d.name)}</span><button class="text-link" data-document="${e(d.name)}">Abrir ↗</button><button data-delete-document="${e(d.name)}" aria-label="Excluir arquivo">×</button></div>`).join('')||empty('Tudo no seu tempo.',s.demo?'Uploads disponíveis apenas para contas conectadas.':'Os arquivos enviados aparecerão aqui.')}</section>`;}

return {home,login,dashboard,profile,universities,shortlist,applications,essays,sat,assistants,documents,guideDetails,catalogResults:()=>catalogResults(s)};
}
