import {agents,groups,escapeHtml as e,nextSlot,validateProfile,profileProgress,wordCount,readiness} from './domain.js';
import {supabase,configured,catalog,loadStudent,unwrap,demoUniversities,demoLoad,demoSave} from './data.js';
import {questions} from './practice.js';
const blank=()=>({profile:null,list:[],tasks:[],essays:[],attempts:[],messages:[]});
const s={...blank(),user:null,demo:false,universities:[],page:'inicio',agent:'universities',search:'',country:'',group:'',catalogPage:0,essayId:null,question:0,feedback:null,docs:[],error:'',busy:false};
const root=document.querySelector('#app');
const nav=[['painel','◉','Meu caminho'],['perfil','◎','Meu perfil'],['universidades','◈','Universidades'],['lista','▤','Minha lista'],['essays','✎','Essays'],['sat','↗','Estudar SAT'],['candidaturas','✓','Candidaturas'],['assistentes','✦','Assistentes'],['documentos','▧','Documentos']];
const link=(page,label,cls='button')=>`<a class="${cls}" href="#${page}">${label}</a>`;
const empty=(title,body)=>`<div class="empty"><span>✧</span><h3>${title}</h3><p>${body}</p></div>`;
const student=()=>Boolean(s.user||s.demo);
const persist=()=>{if(s.demo)demoSave(Object.fromEntries(Object.keys(blank()).map(k=>[k,s[k]])));};
const chip=t=>`<span class="chip">${e(t)}</span>`;
function notify(m){const el=document.querySelector('#notice');el.textContent=m;el.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.hidden=true,7000);}
const fail=err=>{const send=document.querySelector('#chat-form button');if(send&&!s.busy){send.textContent='Enviar ↗';send.disabled=false;}notify(err.message||'Não foi possível concluir. Tente novamente.');};
const head=(label,title,desc,action='')=>`<div class="page-heading"><div><span class="eyebrow">${label}</span><h1>${title}</h1><p>${desc}</p></div>${action}</div>`;
const brand=()=>'<a class="brand" href="#inicio"><b>m<span>↗</span></b><span>meucampus<small>O SEU PRÓXIMO MUNDO</small></span></a>';
function render(){
 if(!['inicio','entrar','universidades'].includes(s.page)&&!student())s.page='entrar';
 const pub=['inicio','entrar'].includes(s.page)||(!student()&&s.page==='universidades');
 const pages={inicio:home,entrar:login,painel:dashboard,perfil:profile,universidades:universities,lista:shortlist,essays:essays,sat:sat,candidaturas:applications,assistentes:assistants,documentos:documents};
 root.innerHTML=`<div class="${pub?'public-shell':'app-shell'}">${pub?`<header>${brand()}<div class="header-links">${link('universidades','Explorar','text-link')}${link(student()?'painel':'entrar',student()?'Meu painel':'Entrar','button primary')}</div></header>`:`<aside class="sidebar">${brand()}<div class="workspace-label">SEU ESPAÇO</div><nav>${nav.map(([id,icon,label])=>`<a href="#${id}" class="${s.page===id?'active':''}"><span>${icon}</span>${label}${id==='lista'?`<small>${s.list.length}/12</small>`:''}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="mini-avatar">${e((s.profile?.full_name||'Você')[0])}</div><div><strong>${e(s.profile?.full_name||'Seu perfil')}</strong><small>${s.demo?'Demonstração':'Conta conectada'}</small></div><button data-action="logout" aria-label="Sair">↪</button></div></aside>`}<main>${pub?'':`<div class="topbar"><span>BRASIL <span class="muted">→</span> MUNDO</span><span>${s.demo?'Demonstração · dados fictícios':'Seu espaço privado'} <b>✦</b></span></div>`}${s.demo?'<div class="demo-banner">Demonstração: universidades fictícias, dados somente neste navegador e respostas de IA desativadas.</div>':''}${s.error?`<div class="error-banner" role="alert">${e(s.error)}</div>`:''}${(pages[s.page]||home)()}</main></div><div id="notice" class="notice" role="status" hidden></div>`;
 bind();
}
function home(){return `<section class="landing"><div><span class="eyebrow">DO BRASIL PARA O SEU PRÓXIMO CAPÍTULO</span><h1>Seu futuro tem<br>um mundo de<br><em>possibilidades.</em></h1><p>Descubra universidades, encontre sua direção e construa uma candidatura com a sua história.</p><div class="actions">${link(student()?'painel':'entrar','Começar minha jornada ↗','button primary')}<button class="button secondary" data-action="demo">Explorar demonstração</button></div><div class="landing-foot"><span>01 · Seu perfil</span><span>02 · Suas escolhas</span><span>03 · Seu próximo passo</span></div></div><div class="journey-art"><div class="globe">↗</div><div class="float-card top"><span class="tiny-icon">✦</span><div>Um plano que é seu<small>Quatro assistentes, uma jornada</small></div></div><div class="float-card bottom"><div class="art-numbers"><b>3<small>SONHO</small></b><b>4<small>POSSÍVEIS</small></b><b>5<small>MAIS ACESSÍVEIS</small></b></div><p>12 escolhas. Um novo horizonte.</p></div><span class="coordinate">23° S &nbsp; → &nbsp; SEU PRÓXIMO DESTINO</span></div></section><section class="landing-features">${Object.values(agents).map(([name,description],i)=>`<article><span>0${i+1} / ✦</span><h3>${name}</h3><p>${description}</p></article>`).join('')}</section><footer>MeuCampus AI · Feito para sua jornada internacional.<span>Orientação com fontes. Sem promessa de aprovação.</span></footer>`;}
function login(){return `<section class="auth-layout"><div><span class="eyebrow">UM PASSO MAIS PERTO</span><h1>O mundo começa<br>com <em>você.</em></h1><p>Crie seu espaço para organizar notas, atividades e candidaturas.</p><div class="auth-note"><b>Seu contexto faz a diferença.</b><p>Vamos considerar o que você já conquistou, onde quer chegar e o apoio financeiro de que precisa.</p></div></div><form id="auth-form" class="panel auth-card"><h2>Entre na sua jornada</h2><p>Use seu e-mail e senha.</p><label>E-mail<input name="email" type="email" autocomplete="email" required></label><label>Senha<input name="password" type="password" autocomplete="current-password" minlength="8" required></label><button class="button primary" name="intent" value="login" ${configured?'':'disabled'}>Entrar →</button><button class="button secondary" name="intent" value="signup" ${configured?'':'disabled'}>Criar conta</button><button type="button" class="text-link" data-action="demo">Conhecer a demonstração</button><p class="small muted">${configured?'Confirme seu e-mail após criar a conta. O compartilhamento de dados com IA é opcional no perfil.':'Configure a conexão do Supabase para ativar o login.'}</p></form></section>`;}
function dashboard(){return `${head('SEU CAMINHO, UM PASSO POR VEZ',`Olá, ${e(s.profile?.full_name?.split(' ')[0]||'viajante')} <span class="accent">✦</span>`,'Você não precisa ter todas as respostas para começar.',link('perfil','Atualizar meu perfil ↗','button secondary'))}<div class="dashboard-hero"><div><span class="eyebrow">SEU PRÓXIMO HORIZONTE</span><h2>Grandes planos.<br>Próximos passos possíveis.</h2><p>Um caminho que considera sua história e suas possibilidades.</p>${link(s.profile?'universidades':'perfil',s.profile?'Explorar universidades ↗':'Completar meu perfil ↗','button lime')}</div><div class="orbit-stat"><strong>${s.list.length}<small>/ 12</small></strong><span>escolhas no seu mapa</span></div></div><div class="metric-grid"><article><span>PERFIL PREENCHIDO</span><strong>${profileProgress(s.profile)}%</strong><div class="meter"><i style="width:${profileProgress(s.profile)}%"></i></div></article><article><span>MEU SAT ATUAL</span><strong>${s.profile?.sat_actual??'—'}</strong><small>Meta: ${s.profile?.sat_target??'a definir'} · cenário futuro</small></article><article><span>AÇÕES CONCLUÍDAS</span><strong>${s.tasks.filter(t=>t.done).length}<small> / ${s.tasks.length}</small></strong><small>Progresso de tarefas, não chance de admissão</small></article></div><div class="two-columns"><section class="panel"><div class="section-title"><h2>O que vem agora</h2>${link('candidaturas','Ver tudo →','text-link')}</div>${taskList(s.tasks.slice(0,4))}</section><section class="panel tint"><span class="eyebrow">SEUS QUATRO ASSISTENTES</span><h2>Uma boa pergunta<br>abre novos caminhos.</h2><p>Universidades, essays, SAT e candidatura: orientação no contexto do seu perfil.</p>${link('assistentes','Escolher um assistente ✦','button secondary')}</section></div>`;}
function field(label,name,type='text',attrs=''){return `<label>${label}<input name="${name}" type="${type}" value="${e(s.profile?.[name]??'')}" ${attrs}></label>`;}
function profile(){return `${head('PASSO 01 · CONTE SUA HISTÓRIA','Seu ponto de partida.','Preencha o que sabe hoje. Você pode atualizar tudo depois.')}<form id="profile-form" class="panel profile-form"><h2>Sobre você</h2><div class="form-grid">${field('Nome *','full_name','text','required maxlength="120"')}${field('Ano ou etapa escolar *','school_year','text','required placeholder="Ex.: 2º ano do ensino médio"')}${field('Conclusão prevista','graduation_year','number','min="2020" max="2100"')}${field('Curso ou área de interesse *','interest','text','required')}<label>Países de interesse<input name="target_countries" value="${e(s.profile?.target_countries?.join(', ')||'')}" placeholder="Estados Unidos, Canadá..."></label>${field('Inglês e provas de proficiência','english_level')}</div><h2>Notas e resultados</h2><p class="small">Use a escala da sua escola. A meta de SAT não conta como resultado realizado.</p><div class="form-grid">${field('Média escolar','grade_average','number','min="0" max="100" step="0.01"')}${field('Nota máxima da escala','grade_scale','number','min="0.01" max="100" step="0.01"')}${field('SAT realizado','sat_actual','number','min="400" max="1600" step="10"')}${field('Meta de SAT','sat_target','number','min="400" max="1600" step="10"')}</div><h2>Atividades e experiências</h2><label>Extracurriculares<textarea name="extracurriculars" rows="6" maxlength="12000" placeholder="Descreva atividade, duração, responsabilidades, horas semanais e resultados reais.">${e(s.profile?.extracurriculars)}</textarea></label><h2>Condições para seu plano</h2><div class="form-grid">${field('Orçamento anual disponível','budget_annual','number','min="0" step="1"')}<label>Moeda<select name="budget_currency">${['BRL','USD','EUR','GBP','CAD'].map(x=>`<option ${x===(s.profile?.budget_currency||'BRL')?'selected':''}>${x}</option>`).join('')}</select></label>${field('Horas semanais para preparação','hours_week','number','min="1" max="80"')}</div><label class="checkbox"><input type="checkbox" name="needs_aid" ${s.profile?.needs_aid?'checked':''}>Preciso de bolsa ou auxílio financeiro.</label><label class="checkbox"><input type="checkbox" name="ai_consent" ${s.profile?.ai_consent?'checked':''}>Permito enviar meu perfil e os textos que eu escolher ao provedor de IA para orientação.</label><p class="small muted">Documentos pessoais não são enviados automaticamente. Você pode desativar esse compartilhamento a qualquer momento.</p><button class="button primary">Salvar meu perfil →</button></form>`;}
function universities(){
 const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const items=s.universities.filter(u=>(!s.country||u.country===s.country)&&(!s.group||u.institutional_group===s.group)&&norm([u.name,u.country,u.institutional_group,...u.courses].join(' ')).includes(norm(s.search)));
 const size=24,total=Math.max(1,Math.ceil(items.length/size));s.catalogPage=Math.min(s.catalogPage,total-1);
 return `${head('PASSO 02 · EXPLORE SEUS DESTINOS','Um mundo para descobrir.','Compare o contexto, as metas do guia e as fontes de cada instituição.',student()?link('lista','Minha lista · '+s.list.length+'/12','button secondary'):link('entrar','Criar minha lista ↗','button primary'))}
 <div class="catalog-tools"><label class="search-label">Buscar universidade ou curso<input id="search" type="search" value="${e(s.search)}" placeholder="Nome, curso ou área de interesse"></label><label>País<select id="country" aria-label="País"><option value="">Todos os países</option>${[...new Set(s.universities.map(u=>u.country))].map(c=>`<option ${s.country===c?'selected':''}>${e(c)}</option>`).join('')}</select></label><label>Tipo de instituição<select id="institution-group" aria-label="Tipo de instituição"><option value="">Todos os tipos</option>${[...new Set(s.universities.map(u=>u.institutional_group).filter(Boolean))].sort().map(c=>`<option ${s.group===c?'selected':''}>${e(c)}</option>`).join('')}</select></label></div>
 <p class="small">${items.length} universidades ${s.demo?'fictícias':`de ${s.universities.length} no catálogo`} · página ${s.catalogPage+1} de ${total}</p>
 ${!s.demo?'<div class="notice-inline">Dados dos materiais fornecidos. As metas do guia não são exigências oficiais. Confirme prazos, bolsas e políticas para o seu ciclo.</div>':''}
 ${items.length?`<div class="university-grid">${items.slice(s.catalogPage*size,(s.catalogPage+1)*size).map((u,i)=>`<article class="university-card"><div class="university-art art-${i%3}"><span>${e(u.name.split(' ').filter(x=>!['of','the','at'].includes(x.toLowerCase())).slice(0,3).map(x=>x[0]).join(''))}</span><small>${e(u.country)}</small></div><div class="university-body">${chip(s.demo?'Exemplo fictício':u.institutional_group||'Graduação internacional')}<h3>${e(u.name)}</h3><p>${e(u.city||u.country)}</p><div class="course-tags">${u.courses.slice(0,3).map(chip).join('')}</div><button class="text-link" data-detail="${e(u.id)}">Explorar e escolher ↗</button></div></article>`).join('')}</div><div class="pagination"><button class="button secondary" data-catalog-page="${s.catalogPage-1}" ${s.catalogPage===0?'disabled':''}>← Anterior</button><span>${s.catalogPage+1} / ${total}</span><button class="button secondary" data-catalog-page="${s.catalogPage+1}" ${s.catalogPage+1===total?'disabled':''}>Próxima →</button></div>`:empty(s.universities.length?'Nenhum resultado para esta busca.':'O catálogo está carregando.','Tente outro nome, curso ou filtro.')}`;
}
function guideDetails(u){
 if(!u.guidance?.classification)return '';
 const g=u.guidance,score=s.profile?.sat_actual,target=Number(g.sat_meta)||null;
 return `<section class="guide-panel"><h3>Metas do guia</h3><p class="small">Sugestões editoriais do material. Não são requisitos nem previsão de aprovação.</p><div class="guide-metrics"><div><small>SAT sugerido</small><b>${e(g.sat_piso||'—')}–${e(g.sat_meta||'—')}</b></div><div><small>Média brasileira sugerida</small><b>${e(g.media_br_alvo||'—')} / 10</b></div><div><small>Admissão geral citada</small><b>${g.taxa_admissao_pct?e(g.taxa_admissao_pct)+'%':'Não informada'}</b></div></div><p class="small">A taxa de admissão geral reúne candidatos e anos diferentes; ela não mede sua chance individual.</p>${score&&target?`<p><b>SAT atual: ${score}.</b> ${score>=target?'Você alcançou a meta editorial. Isso não garante admissão.':`Faltam ${target-score} pontos para a meta editorial de ${target}.`}</p>`:''}<p><b>Direção sugerida:</b> ${e(g.alavanca_principal)}</p><details><summary>Classificação de atividades usada no guia</summary><p>${e(g.nivel_extracurricular)}</p><p class="small">Esta classificação é uma opinião editorial. Uma conquista nacional não é uma obrigação universal; seu contexto e oportunidades precisam ser considerados.</p></details></section>
 ${Object.entries(u.details||{}).map(([name,text])=>`<details class="dossier-section"><summary>${e(name)}</summary><p>${e(text)}</p></details>`).join('')}`;
}
function shortlist(){return `${head('PASSO 03 · CONSTRUA SUA LISTA','12 escolhas. O seu caminho.','Comece pelas 3 sonho, depois 4 possíveis e 5 mais acessíveis.',link('universidades','Explorar universidades ↗','button primary'))}<div class="notice-inline">Categorias são sua estratégia de candidatura. Não são uma previsão validada nem garantia de aprovação.</div><div class="shortlist-grid">${Object.entries(groups).map(([key,g],i)=>`<section class="panel list-group"><span class="eyebrow">0${i+1} · ${s.list.filter(x=>x.category===key).length}/${g.limit}</span><h2>${g.label}</h2><p>${['Onde você quer sonhar alto.','Possibilidades a explorar.','Opções mais favoráveis.'][i]}</p>${Array.from({length:g.limit},(_,slot)=>{const row=s.list.find(x=>x.category===key&&x.slot===slot+1);const u=s.universities.find(x=>x.id===row?.university_id);return row?`<div class="list-item"><span>${slot+1}</span><div><b>${e(u?.name||'Universidade em revisão')}</b><small>${e(u?.country)}</small></div><button data-remove="${e(row.university_id)}" aria-label="Remover ${e(u?.name)}">×</button></div>`:`<a class="list-slot" href="#universidades"><span>+</span> Sua próxima escolha</a>`;}).join('')}</section>`).join('')}</div>`;}
function taskList(tasks){return tasks.length?tasks.map(t=>`<div class="task"><label class="checkbox"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><span class="${t.done?'completed':''}">${e(t.title)}<small>${t.due_on?e(t.due_on.split('-').reverse().join('/')):'Sem prazo definido'}${t.university_id?' · '+e(s.universities.find(u=>u.id===t.university_id)?.name||'Universidade'):''}</small></span></label><button data-delete-task="${t.id}" aria-label="Excluir tarefa">×</button></div>`).join(''):empty('Seu próximo passo começa aqui.','Adicione uma ação na aba Candidaturas.');}
const universityOptions=(selected='')=>'<option value="">Geral</option>'+s.list.map(x=>s.universities.find(u=>u.id===x.university_id)).filter(Boolean).map(u=>`<option value="${u.id}" ${selected===u.id?'selected':''}>${e(u.name)}</option>`).join('');
function applications(){return `${head('DO PLANO À AÇÃO','Sua candidatura ganha forma.','Organize documentos, provas e entregas por universidade.')}<div class="two-columns"><section class="panel"><h2>Próximos passos</h2>${taskList(s.tasks)}</section><form class="panel stack" id="task-form"><h2>Adicionar uma ação</h2><label>O que precisa ser feito?<input name="title" required maxlength="250" placeholder="Ex.: solicitar histórico escolar"></label><label>Prazo<input name="due_on" type="date"></label><label>Universidade<select name="university_id">${universityOptions()}</select></label><button class="button primary">Adicionar ao meu plano +</button><p class="small muted">Confira os prazos na fonte oficial antes de registrar uma data.</p></form></div>`;}
function essays(){const draft=s.essays.find(x=>x.id===s.essayId);return `${head('SUA HISTÓRIA, SUA VOZ','Ideias que merecem espaço.','Desenvolva experiências verdadeiras, com a sua autoria.','<button class="button primary" data-action="new-essay">Novo essay +</button>')}<div class="essay-layout"><aside class="panel essay-index"><h3>Meus textos</h3>${s.essays.map(x=>`<button class="draft-link ${x.id===s.essayId?'selected':''}" data-essay="${x.id}"><b>${e(x.title)}</b><small>${wordCount(x.content)} palavras · versão ${x.version}</small></button>`).join('')||'<p class="small">Seu primeiro rascunho começa aqui.</p>'}</aside><section class="panel">${draft?`<form id="essay-form" class="stack"><label>Título<input name="title" required maxlength="200" value="${e(draft.title)}"></label><div class="form-grid"><label>Universidade<select name="university_id">${universityOptions(draft.university_id)}</select></label><label>Limite de palavras<input name="word_limit" type="number" min="1" max="10000" value="${draft.word_limit}" required></label></div><label>Enunciado<textarea name="prompt" rows="2">${e(draft.prompt)}</textarea></label><label>Seu texto<textarea name="content" id="essay-content" rows="15" maxlength="60000" placeholder="Comece por uma experiência que só você pode contar.">${e(draft.content)}</textarea></label><div class="section-title"><span id="word-count" class="small">${wordCount(draft.content)} / ${draft.word_limit} palavras</span><span class="small muted">Salve antes de sair desta tela.</span></div><div class="actions"><button class="button primary">Salvar rascunho</button><button class="button secondary" type="button" data-action="essay-feedback">Salvar e pedir feedback ✦</button></div></form>`:empty('Cada história começa com um rascunho.','Crie um essay para abrir seu espaço de escrita.')}</section></div>`;}
function sat(){const q=questions[s.question];return `${head('UM POUCO MELHOR A CADA ESTUDO','Encontre seu ritmo no SAT.','Pratique e entenda o raciocínio.')}<div class="metric-grid"><article><span>RESULTADO REALIZADO</span><strong>${s.profile?.sat_actual??'—'}</strong></article><article><span>META PESSOAL</span><strong>${s.profile?.sat_target??'—'}</strong></article><article><span>PRÁTICA REGISTRADA</span><strong>${s.attempts.length}</strong><small>tentativas · não equivale a uma nota SAT</small></article></div><div class="two-columns"><section class="panel"><div class="section-title">${chip(q.skill)}<small>${s.question+1} / ${questions.length}</small></div><h2 class="question">${q.prompt}</h2><form id="practice-form" class="stack">${q.options.map((answer,i)=>`<label class="answer-option"><input type="radio" name="answer" value="${i}" required ${s.feedback!==null?'disabled':''}> <b>${String.fromCharCode(65+i)}</b> ${e(answer)}</label>`).join('')}${s.feedback===null?'<button class="button primary">Conferir resposta →</button>':`<div class="feedback"><b>${s.feedback?'Você acertou.':'Vamos entender esse passo.'}</b><p>${e(q.explanation)}</p></div><button class="button secondary" type="button" data-action="next-question">Próxima questão →</button>`}</form></section><section class="panel tint"><span class="eyebrow">SEU PLANO DE ESTUDO</span><h2>Consistência primeiro.</h2><p>Disponibilidade: ${s.profile?.hours_week??'a definir'} horas por semana.</p><ol class="study-steps"><li>Revise os erros da última sessão.</li><li>Escolha uma habilidade para praticar.</li><li>Resolva questões e explique seu raciocínio.</li><li>Registre o que precisa retomar.</li></ol><button class="button secondary" data-agent="sat">Planejar com o tutor ✦</button><p class="small muted">Banco inicial: 4 exercícios autorais. Não é um simulado oficial.</p><div class="stack"><a class="text-link" href="https://satsuite.collegeboard.org/practice/student-question-bank" target="_blank" rel="noopener noreferrer">Banco oficial de questões ↗</a><a class="text-link" href="https://satsuite.collegeboard.org/practice/practice-tests" target="_blank" rel="noopener noreferrer">Simulados oficiais no Bluebook ↗</a></div></section></div>`;}
function assistants(){const [title,description]=agents[s.agent];const messages=s.messages.filter(x=>x.agent===s.agent);return `${head('QUATRO ESPECIALIDADES · O MESMO CONTEXTO','Um espaço para suas perguntas.','Orientação conectada ao seu perfil e às fontes disponíveis.')}<div class="agent-tabs">${Object.entries(agents).map(([key,[name]])=>`<button data-agent-tab="${key}" class="${key===s.agent?'selected':''}">${name}</button>`).join('')}</div><section class="panel conversation"><div class="section-title"><div><h2>✦ ${title}</h2><p>${description}</p></div></div><div class="chat-messages">${messages.map(m=>`<div class="message user"><small>VOCÊ</small><p>${e(m.question)}</p></div><div class="message assistant"><small>MEUCAMPUS · ${e(agents[m.agent][0])}</small><p>${e(m.answer)}</p>${(m.citations||[]).map(c=>`<small>Fonte: ${e(c.title)} · ${e(c.cycle)} ${c.url&&c.url.startsWith('https://')?`<a href="${e(c.url)}" target="_blank" rel="noopener noreferrer">Abrir ↗</a>`:e(c.document_name||'')+(c.page?' · p. '+e(c.page):'')}</small>`).join('')}</div>`).join('')||empty('Por onde começamos?','Quando faltarem fontes ou informações, o assistente deve deixar isso claro.')}</div><form id="chat-form"><label class="sr-only" for="chat-input">Sua pergunta</label><textarea id="chat-input" name="question" maxlength="6000" required rows="3" placeholder="O que você gostaria de entender?">${e(s.pendingQuestion||'')}</textarea><div class="section-title"><span class="small muted">${s.profile?.ai_consent?'Seu perfil autorizado será usado como contexto.':'Ative o consentimento de IA no seu perfil para conversar.'}</span><button class="button primary" ${s.busy?'disabled':''}>${s.busy?'Preparando resposta…':'Enviar ↗'}</button></div></form></section>`;}
function documents(){return `${head('SEUS DOCUMENTOS, EM UM SÓ LUGAR','Organize o que conta sua história.','Arquivos privados, acessíveis somente pela sua conta.')}<section class="panel"><form id="upload-form" class="upload-form"><label>Histórico, comprovante ou documento<input type="file" name="file" accept="application/pdf,image/png,image/jpeg" required></label><button class="button primary" ${s.demo?'disabled':''}>Enviar arquivo ↑</button></form><p class="small muted">PDF, PNG ou JPEG · até 10 MB. Os documentos não são enviados automaticamente às IAs.</p>${s.docs.map(d=>`<div class="document-row"><span>${e(d.name)}</span><button class="text-link" data-document="${e(d.name)}">Abrir ↗</button><button data-delete-document="${e(d.name)}" aria-label="Excluir arquivo">×</button></div>`).join('')||empty('Tudo no seu tempo.',s.demo?'Uploads disponíveis apenas para contas conectadas.':'Os arquivos enviados aparecerão aqui.')}</section>`;}
async function detail(id){const u=s.universities.find(x=>x.id===id);if(!u)return;if(!s.demo&&!u.details){const data=await unwrap(supabase.from('universities').select('details,university_sources(*)').eq('id',id).single());Object.assign(u,data);}document.querySelector('dialog')?.remove();const d=document.createElement('dialog');d.innerHTML=`<button class="close" aria-label="Fechar">×</button><span class="eyebrow">${e(u.country)} · ${e(u.cycle)}</span><h2>${e(u.name)}</h2><p>${e(u.summary||'Descrição não disponível.')}</p>${guideDetails(u)}<h3>Seu perfil e esta opção</h3><ul>${readiness(s.profile,u).map(x=>`<li>${e(x)}</li>`).join('')}</ul>${s.profile?.sat_target?`<details><summary>Simular com minha meta de SAT (${s.profile.sat_target})</summary><ul>${readiness(s.profile,u,s.profile.sat_target).map(x=>`<li>${e(x)}</li>`).join('')}</ul><p class="small">Simulação. Seu resultado atual permanece inalterado.</p></details>`:''}<h3>Fontes disponíveis</h3>${u.university_sources?.map(f=>`<p class="small">${e(f.title)} · ${e(f.cycle)} · ${f.status==='verified'?'Verificada':'Material fornecido'}<br>${e(f.excerpt)}<br>${f.url?`<a href="${e(f.url)}" target="_blank" rel="noopener noreferrer">Consultar fonte ↗</a>`:e(f.document_name)+(f.page?' · p. '+e(f.page)+(f.page_end?'–'+e(f.page_end):''):' · registro '+e(f.record_number))}</p>`).join('')||'<p class="small">Nenhuma fonte verificada disponível para esta análise.</p>'}${!student()?link('entrar','Entrar para salvar esta escolha','button primary'):s.list.some(x=>x.university_id===id)?'<p class="chip">Já está na sua lista</p>':`<form id="choice-form"><label>Adicionar em<select name="category">${Object.entries(groups).map(([key,g])=>`<option value="${key}">${g.label} · ${s.list.filter(x=>x.category===key).length}/${g.limit}</option>`).join('')}</select></label><button class="button primary">Adicionar à minha lista +</button><p id="choice-error" role="alert"></p></form>`}`;document.body.append(d);d.showModal();d.querySelector('.close').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.querySelector('a[href="#entrar"]')?.addEventListener('click',()=>d.close());d.querySelector('form')?.addEventListener('submit',async ev=>{ev.preventDefault();const b=ev.target.querySelector('button');b.disabled=true;try{const category=new FormData(ev.target).get('category');const row={university_id:id,category,slot:nextSlot(s.list,category,id)};if(!s.demo)await unwrap(supabase.from('student_universities').insert({...row,user_id:s.user.id}));s.list.push(row);persist();d.close();render();notify('Escolha adicionada.');}catch(err){d.querySelector('#choice-error').textContent=err.message;}finally{b.disabled=false;}});}
async function saveEssay(){const form=document.querySelector('#essay-form');if(!form?.reportValidity())return false;const draft=s.essays.find(x=>x.id===s.essayId);const v=Object.fromEntries(new FormData(form));v.word_limit=Number(v.word_limit);v.university_id=v.university_id||null;v.version=draft.version+1;v.updated_at=new Date().toISOString();if(!s.demo){const rows=await unwrap(supabase.from('essays').update(v).eq('id',draft.id).eq('version',draft.version).select());if(!rows.length)throw new Error('Texto alterado em outra sessão. Copie seu rascunho antes de recarregar.');}Object.assign(draft,v);persist();return true;}
async function refreshDocs(){if(s.user&&!s.demo)s.docs=await unwrap(supabase.storage.from('student-documents').list(s.user.id));}
function guarded(form,handler){form?.addEventListener('submit',async ev=>{ev.preventDefault();const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await handler(ev);}catch(err){fail(err);}finally{buttons.forEach(b=>b.disabled=false);}});}
async function action(a){
 if(a==='demo'){sessionStorage.setItem('mc-demo','1');s.demo=true;s.user=null;s.country='';s.search='';s.group='';s.catalogPage=0;Object.assign(s,blank(),demoLoad());s.error='';s.universities=demoUniversities;location.hash='painel';render();}
 if(a==='logout'){sessionStorage.removeItem('mc-demo');if(!s.demo)await supabase.auth.signOut();Object.assign(s,blank(),{user:null,demo:false,docs:[],universities:[]});location.hash='inicio';s.universities=await catalog();}
 if(a==='new-essay'){const draft={id:crypto.randomUUID(),title:'Meu novo essay',prompt:'',content:'',word_limit:650,version:1,university_id:null};if(!s.demo)await unwrap(supabase.from('essays').insert({...draft,user_id:s.user.id}));s.essays.unshift(draft);s.essayId=draft.id;persist();render();}
 if(a==='essay-feedback'&&await saveEssay()){const draft=s.essays.find(x=>x.id===s.essayId);if(draft.content.length>4500)throw new Error('Essay salvo. Para feedback, envie um trecho de até 4.500 caracteres ao mentor.');s.agent='essays';s.pendingQuestion='Revise clareza, estrutura e autenticidade. Não invente experiências. Enunciado: '+draft.prompt.slice(0,700)+'\nTexto: '+draft.content;location.hash='assistentes';}
 if(a==='next-question'){s.question=(s.question+1)%questions.length;s.feedback=null;render();}
}
function bind(){
 document.querySelectorAll('.sidebar nav a').forEach((a,i)=>a.setAttribute('aria-label',nav[i][2]));
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action).catch(fail));
 guarded(document.querySelector('#auth-form'),async ev=>{const f=new FormData(ev.target);const c={email:f.get('email'),password:f.get('password')};const {data,error}=await (ev.submitter?.value==='signup'?supabase.auth.signUp(c):supabase.auth.signInWithPassword(c));if(error)throw error;if(!data.session){notify('Confira seu e-mail para confirmar o cadastro.');return;}sessionStorage.removeItem('mc-demo');s.user=data.user;s.demo=false;Object.assign(s,await loadStudent(s.user.id));s.universities=await catalog();location.hash=s.profile?'painel':'perfil';});
 guarded(document.querySelector('#profile-form'),async ev=>{const p=Object.fromEntries(new FormData(ev.target));for(const k of ['graduation_year','grade_average','grade_scale','sat_actual','sat_target','budget_annual','hours_week'])p[k]=p[k]===''?null:Number(p[k]);p.needs_aid=Boolean(p.needs_aid);p.ai_consent=Boolean(p.ai_consent);p.target_countries=p.target_countries.split(',').map(x=>x.trim()).filter(Boolean);p.updated_at=new Date().toISOString();validateProfile(p);if(!s.demo)await unwrap(supabase.from('student_profiles').upsert({...p,user_id:s.user.id}));s.profile=p;persist();location.hash='painel';});
 document.querySelector('#search')?.addEventListener('input',ev=>{s.search=ev.target.value;s.catalogPage=0;render();document.querySelector('#search').focus();});
 document.querySelector('#country')?.addEventListener('change',ev=>{s.country=ev.target.value;s.catalogPage=0;render();});
 document.querySelector('#institution-group')?.addEventListener('change',ev=>{s.group=ev.target.value;s.catalogPage=0;render();});
 document.querySelectorAll('[data-catalog-page]').forEach(b=>b.onclick=()=>{s.catalogPage=Number(b.dataset.catalogPage);render();scrollTo(0,0);});
 document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail).catch(fail));
 document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{try{if(!s.demo)await unwrap(supabase.from('student_universities').delete().eq('user_id',s.user.id).eq('university_id',b.dataset.remove));s.list=s.list.filter(x=>x.university_id!==b.dataset.remove);persist();render();}catch(err){fail(err);}});
 guarded(document.querySelector('#task-form'),async ev=>{const v=Object.fromEntries(new FormData(ev.target));const t={...v,id:crypto.randomUUID(),due_on:v.due_on||null,university_id:v.university_id||null,done:false};if(!s.demo)await unwrap(supabase.from('tasks').insert({...t,user_id:s.user.id}));s.tasks.push(t);persist();render();notify('Ação adicionada.');});
 document.querySelectorAll('[data-task]').forEach(b=>b.onchange=async()=>{try{const t=s.tasks.find(x=>x.id===b.dataset.task);if(!s.demo)await unwrap(supabase.from('tasks').update({done:b.checked}).eq('id',t.id));t.done=b.checked;persist();render();}catch(err){b.checked=!b.checked;fail(err);}});
 document.querySelectorAll('[data-delete-task]').forEach(b=>b.onclick=async()=>{try{if(!s.demo)await unwrap(supabase.from('tasks').delete().eq('id',b.dataset.deleteTask));s.tasks=s.tasks.filter(t=>t.id!==b.dataset.deleteTask);persist();render();}catch(err){fail(err);}});
 document.querySelectorAll('[data-essay]').forEach(b=>b.onclick=()=>{s.essayId=b.dataset.essay;render();});
 guarded(document.querySelector('#essay-form'),async()=>{if(await saveEssay())notify('Rascunho salvo.');});
 document.querySelector('#essay-content')?.addEventListener('input',ev=>{const n=wordCount(ev.target.value),limit=document.querySelector('[name=word_limit]').value;document.querySelector('#word-count').textContent=n+' / '+limit+' palavras'+(n>limit?' · acima do limite':'');});
 guarded(document.querySelector('#practice-form'),async ev=>{const q=questions[s.question],chosen=Number(new FormData(ev.target).get('answer'));const row={id:crypto.randomUUID(),question_id:q.id,chosen,correct:chosen===q.answer,skill:q.skill};if(!s.demo)await unwrap(supabase.from('sat_attempts').insert({...row,user_id:s.user.id}));s.attempts.push(row);s.feedback=row.correct;persist();render();});
 document.querySelectorAll('[data-agent]').forEach(b=>b.onclick=()=>{s.agent=b.dataset.agent;location.hash='assistentes';});
 document.querySelectorAll('[data-agent-tab]').forEach(b=>b.onclick=()=>{s.agent=b.dataset.agentTab;s.pendingQuestion='';render();});
 guarded(document.querySelector('#chat-form'),async ev=>{if(s.demo)throw new Error('Entre em uma conta conectada para conversar com a IA.');if(!s.profile?.ai_consent)throw new Error('Ative o compartilhamento com IA no seu perfil.');const question=new FormData(ev.target).get('question'),agent=s.agent,userId=s.user.id;s.busy=true;ev.target.querySelector('button').textContent='Preparando resposta…';try{const {data,error}=await supabase.functions.invoke('counselor',{body:{agent,question}});if(error){let message='Não foi possível consultar o assistente.';try{message=(await error.context.json()).error||message;}catch{}throw new Error(message);}if(data.error)throw new Error(data.error);if(s.user?.id!==userId||s.demo)return;s.messages.push({question,agent,...data});s.pendingQuestion='';}finally{s.busy=false;}render();});
 guarded(document.querySelector('#upload-form'),async ev=>{const f=new FormData(ev.target).get('file');if(!f?.size||f.size>10485760)throw new Error('Selecione um arquivo de até 10 MB.');if(!['application/pdf','image/png','image/jpeg'].includes(f.type))throw new Error('Use PDF, PNG ou JPEG.');const name=crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');await unwrap(supabase.storage.from('student-documents').upload(s.user.id+'/'+name,f));await refreshDocs();render();notify('Arquivo salvo.');});
 document.querySelectorAll('[data-document]').forEach(b=>b.onclick=async()=>{try{const d=await unwrap(supabase.storage.from('student-documents').createSignedUrl(s.user.id+'/'+b.dataset.document,60));window.open(d.signedUrl,'_blank','noopener,noreferrer');}catch(err){fail(err);}});
 document.querySelectorAll('[data-delete-document]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir este arquivo?'))return;try{await unwrap(supabase.storage.from('student-documents').remove([s.user.id+'/'+b.dataset.deleteDocument]));await refreshDocs();render();}catch(err){fail(err);}});
}
addEventListener('hashchange',async()=>{s.page=location.hash.slice(1)||'inicio';render();scrollTo(0,0);if(s.page==='documentos'){try{await refreshDocs();render();}catch(err){fail(err);}}});
async function start(){
 if(sessionStorage.getItem('mc-demo')==='1'){s.demo=true;Object.assign(s,blank(),demoLoad());s.universities=demoUniversities;s.page=location.hash.slice(1)||'painel';render();return;}
 render();try{const items=await catalog();if(s.demo)return;s.universities=items;
 if(supabase){const {data,error}=await supabase.auth.getSession();if(error)throw error;if(s.demo)return;s.user=data.session?.user||null;if(s.user)Object.assign(s,await loadStudent(s.user.id));}
 if(s.demo)return;s.page=location.hash.slice(1)||'inicio';render();if(s.page==='documentos'){await refreshDocs();render();}
 }catch(err){if(s.demo)return;s.error='Não foi possível carregar os dados: '+err.message;render();}}
start();
